### ISSUE TITLE
Flatpak Steam sometimes starts games as superuser.

### ISSUE THREAD

**Issue by good-old-music** [flathub/com.valvesoftware.Steam#244]
Occasionally a game will start and it has the title followed by (as superuser) on the menu bar - obviously being aware of this occurring I immediately kill the game and re-start.

This is however a serious risk and needs to be looked for when starting games.

How does flatpak steam gain access to superuser? - it has never had access to the password and doesn't ask for one. Sudo is not installed. Desktop requires password every time for elevated privileges somehow Flatpak steam avoids this. 

This has been happening for the last year on and off.

Flatpak installed via apt,
Flathub is a named repository.
Steam installed as regular user.

System info:
OS: Debian Buster (testing branch)
Desktop: Mate 1.20.3
Kernel: 4.18.01 (amd64)
Processor: Intel® Xeon(R) CPU E3-1240 V2 @ 3.40GHz × 8

**Comment by nanonyme** [comment]
This sounds like a probable in privilege reporting though could also be an issue in Flatpak. Flatpak uses an elevated helper to set up a sandbox inside which applications like Steam is run. You need root to set up the sandbox but in reality applications inside the sandbox are less privileged than your user, not more.

If you want to debug further, file a bug against flatpak/flatpak instead of this project. This has absolutely nothing to do with the application and core devs aren't following this issue tracker

**Comment by nanonyme** [comment]
Note the reason why privileges are gained by Flatpak without password is Flatpak includes a setuid helper

**Comment by good-old-music** [comment]
Okay, cheers for that.
