### ISSUE TITLE
No sound in Bastion

### ISSUE THREAD

**Issue by jurf** [flathub/com.valvesoftware.Steam#31]
This is the output I get:
```
❯ flatpak run --command=sh com.valvesoftware.Steam
sh-4.3$ cd /data/games/steamapps/common/Bastion/Linux/             
sh-4.3$ ./Bastion.bin.x86 
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
Number of joysticks: 0
initializing c# fmod
ALSA lib dlmisc.c:254:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so
FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called. 
FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called. 
FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called. 
FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called. 
FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called. 
FMOD error! ERR_UNINITIALIZED - This command failed because System::init or System::setDriver was not called. 
sh-4.3$ 
```

**Comment by Unrud** [comment]
``/usr/lib/alsa-lib/libasound_module_pcm_pulse.so`` is a 64-bit library. If I start ``./Bastion.bin.x86_64`` instead, the sound works.

**Comment by jurf** [comment]
@Unrud how did you achieve that? I mean, is it possible to do with the Steam GUI?

**Comment by jurf** [comment]
@Unrud oh wait, Steam _does_ use the 64 bit version by default, and still the sound doesn’t work.

**Comment by Unrud** [comment]
> Steam does use the 64 bit version by default, and still the sound doesn’t work.

Yes, but it works when you start the 64-bit version without the Steam runtime. (As you did with the 32-bit version.)

When Bastion is launched with the Steam runtime, it loads the following libraries:

* ``/lib/libasound.so``
* ``/usr/lib/alsa-lib/libasound_module_pcm_pulse.so``
* ``~/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libpulse.so.0``
* ``/usr/lib/pulseaudio/libpulsecommon-10.0.so``

This seems wrong. ``/usr/lib/pulseaudio/libpulsecommon-10.0.so`` is loaded directly, without searching library paths. The steam runtime only has ``libpulsecommon-1.1.so``.

The ALSA Pulse module should always load ``/usr/lib/libpulse.so.0`` instead of searching library paths for it.

**Comment by jurf** [comment]
Huh, interesting. Yeah, just tried Bastion x64 Steamless and it worked fine, but I don’t know why it works normally in a non-flatpak installation.

**Comment by Unrud** [comment]
I've tested the game on Fedora 26: The game doesn't use the Steam runtime and the sound works.

Interestingly it uses ``libpulse-simple.so.0`` instead of ``libasound.so``.

**Comment by jurf** [comment]
BTW I tried the symlink and it worked, so there’s that at least.

**Comment by jurf** [comment]
Seems working now, Thomas Was Alone is fixed too, thanks!
