### ISSUE TITLE
Steam doesn't appear on Fedora 25 with legacy NVidia drivers

### ISSUE THREAD

**Issue by mavit** [flathub/com.valvesoftware.Steam#35]
When I try to run `flatpak`ed Steam on Fedora 25 x86_64 with NVidia graphics and the 340.104 driver, no window appears.  Instead, I see the following messages on the terminal:

```
> flatpak run com.valvesoftware.Steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1507158695)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

This suggests I might be missing some libraries, but I believe I have everything I need:

```
> flatpak --gl-drivers
nvidia-340-104
default
host
> flatpak list                                                         Ref                                                     Options     
com.valvesoftware.Steam/x86_64/stable                   user,current
org.freedesktop.Platform.Compat32/x86_64/1.6            user,runtime
org.freedesktop.Platform.GL.nvidia-340-104/x86_64/1.4   user,runtime
org.freedesktop.Platform.GL32.nvidia-340-104/x86_64/1.4 user,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6         user,runtime
org.freedesktop.Platform/x86_64/1.6                     user,runtime
```

I have another machine running Fedora 26 and more recent hardware, on which I believe I've done the same things, on which Steam starts up fine.  Is there something I could do to try to debug this, a troubleshooting guide or suchlike?

**Comment by TingPing** [comment]
This driver version was added a few days ago, it may take a bit to get sync'd though I'll see if I can get that to happen tomorrow.

**Comment by Zakhrov** [comment]
I have a similar issue with default mesa drivers after running flatpak update
`Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1508910373)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

`

**Comment by legacychimera247** [comment]
have the same issue in fedora 26 with mesa...just out of note i've just done a fresh install but before this fresh install steam was working like s charm...

**Comment by TingPing** [comment]
This is probably an issue that should be reported on the flatpak repo as it is just OpenGL in general failing to load.

**Comment by pablodav** [comment]
I'm not sure if it is an issue with mesa installation or with steam package, in my case both: steam from flatpak and installed steam gives same problem. 

debugging information: 

```
LIBGL_DEBUG=verbose flatpak run com.valvesoftware.Steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1508882027)
libGL: Can't open configuration file /home/pablo/.drirc: No such file or directory.
libGL: pci id for fd 8: 1002:699f, driver radeonsi
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/radeonsi_dri.so
libGL: dlopen /app/lib/32bit/lib/dri/radeonsi_dri.so failed (/home/pablo/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /app/lib/32bit/lib/libLLVMSupport.so.4))
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/swrast_dri.so
libGL: dlopen /app/lib/32bit/lib/dri/swrast_dri.so failed (/home/pablo/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /app/lib/32bit/lib/libLLVMSupport.so.4))
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by pablodav** [comment]
Now I have detected that one of these files are poiting to wrong libstdc version: 

```
file /home/pablo/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
/home/pablo/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: symbolic link to libstdc++.so.6.0.21
[pablo@192 ~]$ ls -l /usr/lib64/libstdc++.so.6.0.21
ls: no se puede acceder a '/usr/lib64/libstdc++.so.6.0.21': No such file or directory
[pablo@192 ~]$ ls -l /usr/lib64/libstdc++.so.6.0.24 
-rwxr-xr-x. 1 root root 1586584 set 15 09:05 /usr/lib64/libstdc++.so.6.0.24
```
Will check later how to workaround it.

**Comment by syjer** [comment]
I have the same issue with fedora 26:

```
LIBGL_DEBUG=verbose flatpak run com.valvesoftware.Steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1504757234)
libGL: Can't open configuration file /home/sylvain/.drirc: No such file or directory.
libGL: pci id for fd 8: 1002:6810, driver radeonsi
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/radeonsi_dri.so
libGL: dlopen /app/lib/32bit/lib/dri/radeonsi_dri.so failed (/home/sylvain/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /app/lib/32bit/lib/libLLVMSupport.so.4))
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /app/lib/32bit/lib/dri/swrast_dri.so
libGL: dlopen /app/lib/32bit/lib/dri/swrast_dri.so failed (/home/sylvain/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /app/lib/32bit/lib/libLLVMSupport.so.4))
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

At the moment, I've found the following workaround: remove the symlink and the library (for both x86 and 64bit variant)

```
cd ~/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/
rm libstdc++.so.6
rm libstdc++.so.6.0.21
cd ~/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/
rm libstdc++.so.6
rm libstdc++.so.6.0.21
```

Ugly, but it works...

**Comment by pablodav** [comment]
You are right, same thing fixes steam for me and also games plays. 
Don't know why this embedded library breaks steam, but looks like it could be reported upstream? or workaround should be added in flatpak?

**Comment by nanonyme** [comment]
Sounds closely like libstdc++ versioning conflict between Mesa and Steam. Iirc @TingPing set some always prefer runtime environment variable which might be the root cause

**Comment by steffenWi** [comment]
Arch Linux user here. After updating flatpak I have the same issue. My native Steam installation is fine though (aside from not starting various games obviously).

**Comment by TingPing** [comment]
If everybody could be on flatpak 0.10 and update steam and test again that would be appreciated.

**Comment by steffenWi** [comment]
Yes, updating to flatpak 0.10, then issued 

> flatpak update com.valvesoftware.Steam

and it works again. Thank you very much for fixing it. What was the issue?

**Comment by legacychimera247** [comment]
today i've downloaded a little update and steam started again, after having launched steam i signed in for beta updates and updated steam...now it not launching again...i just get the connect to the account box then it disappear and steamwill not launch...this is what i get in terminal

`Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Gtk-Message: Failed to load module "pk-gtk-module"
Installing breakpad exception handler for appid(steam)/version(1509425745)
surface_linux.cpp (2082) : Assertion Failed: None of the authentication protocols specified are supported
Assert( Assertion Failed: None of the authentication protocols specified are supported ):surface_linux.cpp:2082

Installing breakpad exception handler for appid(steam)/version(1509425745)
No minidump written, nothing to upload.
[1102/161150.094154:ERROR:proxy_config_service_linux.cc(272)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown

Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)

** (steam:110): WARNING **: Unknown device type 13

** (steam:110): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:110): WARNING **: handle_property_changed: failed to update property 'devices' of object type NMActiveConnection.

** (steam:110): WARNING **: Unknown device type 14

** (steam:110): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/1: unknown object type

** (steam:110): WARNING **: Unknown device type 13

** (steam:110): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/4: unknown object type

** (steam:110): WARNING **: Unknown device type 16

** (steam:110): WARNING **: Could not create object for /org/freedesktop/NetworkManager/Devices/5: unknown object type
[1102/161152.124601:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Installing breakpad exception handler for appid(steam)/version(1509425745)

** (steam:110): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:110): WARNING **: Ignoring invalid property 'interface-name'

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'interface-name'

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Unknown setting 'bridge'

** (steam:110): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/4 settings: (3) type

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'autoconnect-priority'

** (steam:110): WARNING **: Ignoring invalid property 'interface-name'

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'interface-name'

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'dns-priority'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Unknown setting 'bridge'

** (steam:110): WARNING **: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/4 settings: (3) type

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Unknown setting 'proxy'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'

** (steam:110): WARNING **: Ignoring invalid property 'route-data'

** (steam:110): WARNING **: Ignoring invalid property 'address-data'
[1102/161153.125594:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
Installing breakpad exception handler for appid(steam)/version(1509425745)
[1102/161154.126588:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198043478263 [API loaded no]
[1102/161155.128206:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
Installing breakpad exception handler for appid(steam)/version(1509425745)
roaming config store loaded successfully - 3355 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1509425745)
Failed to init SteamVR because it isn't installed
sh: lspci: command not found
process 110: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2686.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
[2017-11-02 16:11:37] Startup - updater built Oct 30 2017 19:09:32
[2017-11-02 16:11:37] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-11-02 16:11:37] Checking for update on startup
[2017-11-02 16:11:37] Checking for available updates...
[2017-11-02 16:11:38] Download skipped: /client/steam_client_publicbeta_ubuntu12 version 1509425745, installed version 1509425745
[2017-11-02 16:11:38] Nothing to do
[2017-11-02 16:11:38] Verifying installation...
[2017-11-02 16:11:38] Performing checksum verification of executable files
[2017-11-02 16:11:47] Verification complete
No minidump written, nothing to upload.
/home/luca247/.var/app/com.valvesoftware.Steam/data/Steam/steam.sh: line 941:   110 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
Assert( Assertion Failed: m_pInternalPipe->BRead failed ):../common/pipes.cpp:572

No minidump written, nothing to upload.
Forced create but already created for SharedObjectEvent
../common/pipes.cpp (572) : Assertion Failed: m_pInternalPipe->BRead failed`

**Comment by rowbawts** [comment]
Similar issue as above updated the Steam Flatpak earlier today and ever since then I've just been getting this:

```
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1509425745)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```

**Comment by valentindavid** [comment]
It is not clear whether everyone has the same bug. If each one who commented could do this:
 - give the output of "flatpak --version"
 - give the output of "flatpak --gl-drivers"
 - try with "FLATPAK_GL_DRIVERS=none flatpak run com.valvesoftware.Steam". And if it works, tell us!

We remind you that flatpak 0.10 or more is required for Steam. We unfortunately do not support 0.8 anymore so we could properly fix sound problems and fix crashes happening with amdgpu.

**Comment by rowbawts** [comment]
```
bronze@hardware:~/Games$ flatpak --version
Flatpak 0.10.0
bronze@hardware:~/Games$ flatpak --gl-drivers
nvidia-384-90
default
host
```

Running with that command as recommended doesn't work.

**Comment by valentindavid** [comment]
Thanks. Could you also provide "flatpak list -d"?

**Comment by rowbawts** [comment]
```
com.valvesoftware.Steam/x86_64/stable                  flathub 93dacf895d8d  -               2.9 MB       system,current
org.freedesktop.Platform.Compat32/x86_64/1.6           flathub 8fb9921dd45a  -             576.3 MB       system,runtime
org.freedesktop.Platform.GL.nvidia-384-90/x86_64/1.4   flathub 69d7cd236808  -             980.0 kB       system,runtime
org.freedesktop.Platform.GL32.nvidia-384-90/x86_64/1.4 flathub ddbb70892d15  -             848.9 kB       system,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6        flathub 5962b0bb8996  -               7.8 MB       system,runtime
org.freedesktop.Platform/x86_64/1.6                    flathub dd96e277be2d  -             560.2 MB       system,runtime
```

**Comment by valentindavid** [comment]
OK, thanks. I will try to reproduce that this weekend.

**Comment by rowbawts** [comment]
Anyway I can downgrade so I can get it working until it's resolved?

**Comment by pablodav** [comment]
@legacychimera247 , I had problems to run steambeta too, but fixed reverting back to normal steam, doing it:

```shell
bash-4.4$ rm -rf .var/app/com.valvesoftware.Steam/data/Steam/config/
bash-4.4$ rm -rf .var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/
bash-4.4$ rm -rf .var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_64/
bash-4.4$ flatpak run com.valvesoftware.Steam
```

It ran correctly. 

```
bash-4.4$ flatpak --gl-drivers
default
host
bash-4.4$ flatpak --version
Flatpak 0.10.0
```

```shell
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX 550 Series (AMD POLARIS12 / DRM 3.18.0 / 4.13.10-300.fc27.x86_64, LLVM 4.0.1) (0x699f)
    Version: 17.2.4
    Accelerated: yes
    Video memory: 2022MB
    Unified memory: no
```

**Comment by legacychimera247** [comment]
ok...what about fedora?

**Comment by valentindavid** [comment]
OK. So I have updated Steam through flatpak on a machine with an nvidia card. I got the same bug. Then I removed files from .var/app/com.valvesoftware.Steam/data/Steam and re-installed (backed up subdirectory steamapps). And then it worked.

I am not sure what the problem is. Steam was not originally installed as beta, so it is not the beta that is the problem.

@rowbawts, Could you try to do the same operation (or @pablodav's) and see if it helps?

**Comment by rowbawts** [comment]
@valentindavid That actually worked thanks for finding a solution, but still I wonder why that happened?

**Comment by pablodav** [comment]
thanks @valentindavid for the steps, 
I didn't use those, but discovered this --reset flag now: 

```
flatpak run com.valvesoftware.Steam --reset
+ GLOBIGNORE='*/.steam:*/.local:*/.var'
+ cp -a /home/pablo/.var/app/com.valvesoftware.Steam/home/pablo /home/pablo/
+ rm -r /home/pablo/.var/app/com.valvesoftware.Steam/home
+ unset GLOBIGNORE
+ set +x
Installing bootstrap /home/pablo/.var/app/com.valvesoftware.Steam/data/Steam/bootstrap.tar.xz
Reset complete!
```

After that I have running steam and it just started fine. (even on beta channel)

**Comment by mavit** [comment]
I confirm that Steam starts correctly after upgrading to Fedora 27 (which incorporates Flatpak 0.10.0).
