### ISSUE TITLE
When ~/.var is a symlink, Steam only launches the first time

### ISSUE THREAD

**Issue by jimmac** [flathub/com.valvesoftware.Steam#386]
When I try to launch Steam I get:

```
$ flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/jimmac/.var: File exists

```

Due to space constraints my `~/.var` lives on a larger volume than my `/home` and is symlinked, thus this is a rather corner case issue. The interesting part is that when I delete `.var/app/com.valvesoftware.Steam` and launch it, it installs the Steam bits and launches and runs fine. Until I quit it and try to launch it again.

This is Fedora 30 running Flatpak 1.4.2

**Comment by nanonyme** [comment]
Have you considered instead doing https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#i-want-to-add-external-disk-for-steam-libraries?

**Comment by jimmac** [comment]
That's a workaround that might work for Steam, but not all my other apps.

**Comment by Erick555** [comment]
I think you may use `mount --bind` (in fstab) instead of symlink like:
`/some/volume/path /home/jimmac/.var none bind 0 0`

**Comment by jimmac** [comment]
Thanks for the tip. However the problem just morphed into another:

```
$ mount | grep \\.var
/dev/sdb1 on /home/jimmac/.var type ext4 (rw,relatime)
~/.var
$ ls ~/.var/
app
~/.var
$ flatpak run com.valvesoftware.Steam
bwrap: Can't mkdir /home/jimmac/.var/app: No such file or directory
```

**Comment by nanonyme** [comment]
Do your other apps take non-negligible amounts of space? I was assuming the problem is mostly with games taking gigabytes of space.

**Comment by jimmac** [comment]
Yes I have apps taking gigabytes of space and they all work fine:

```
14G	com.valvesoftware.Steam
66G	org.gnome.BoxesDevel
7.7G	org.gnome.Builder
17G	com.blizzard.StarCraft2
2.6G	com.albiononline.AlbionOnline
```

**Comment by nanonyme** [comment]
Original issue possibly related to https://github.com/flathub/com.valvesoftware.Steam/issues/57

**Comment by nanonyme** [comment]
I suspect latter is related to path create order in sandbox.

**Comment by user5145** [comment]
it's not limited to ~/.var
bwrap: Can't make symlink at /home/user5145/Storage: File exists

ll:
Storage -> /mnt/storage

**Comment by nanonyme** [comment]
Sorry, I meant I meant to say I was assuming the home directory space issue was only relevant for Steam. I didn't mean to say I expected other games to suffer of same symlinking issue. This app does quite complicated things to allow Steam Cloud to work for all games and it might be some assumptions are off in this case. I don't really have time to debug for now so I would suggest considering instead of symlinking entire var to consider only symlinking individual apps. Might also make sense to request at https://github.com/flatpak/flatpak/issues level a way to re-home applications instead of playing around with symlinks.

**Comment by jimmac** [comment]
It's quite a corner case scenario and probably not worth spending too much time on.
