### ISSUE TITLE
Remove repair_broken_migration() from the wrapper?

### ISSUE THREAD

**Issue by gasinvein** [flathub/com.valvesoftware.Steam#607]
The wrapper script with broken migration logic existed for 5 days 2 years ago (since 1994a4d38d190a5956c44babc2ea54fe2782905d till 8e651443a66d69bd06a73cc0625c72349a1c8bd6). I guess it's very unlikely that there are still users who installed Steam flatpak in that time window and still didn't update or uninstall it.
Maybe the logic to repair broken migration isn't useful anymore and should be removed?

**Comment by nanonyme** [comment]
Sure, let's remove it. Just need to be careful to leave actual migration in place.

**Comment by nanonyme** [comment]
There's also some more code that could possibly be removed like the asking for consent for migration.

1. At this point everyone who hasn't accepted has stopped using the app since you can't use app without accepting
2. Everyone else has migrated
3. The only danger is if you expose your real home to the app and we try to sanitize --filesystem so that home is not exposed. Maybe we should be better at it though.
