### ISSUE TITLE
Controllers not detected by Steam

### ISSUE THREAD

**Issue by PureTryOut** [flathub/com.valvesoftware.Steam#699]
Since a while, probably a few months actually, Steam in Flatpak for some reason doesn't see my controllers anymore (DualShock 4's). The Steam controller configuration page says none are detected, but if I launch Steam outside of Flatpak they are detected and work fine.

And since Steam doesn't pick up the controllers, neither do any games.

**Comment by romulasry** [comment]
Same problem with PS4 controller with flatpak steam.

**Comment by BrainBlasted** [comment]
Same issue with the Steam Controller

**Comment by erazemk** [comment]
You can solve this issue by enabling the "D-Bus system bus" option for Steam in Flatseal (as shown below) or by running the appropriate flatpak command.

It works for my Logitech gamepad, so it should probably work for your gamepads as well if they work normally outside of flatpak without any modifications.

![steam](https://user-images.githubusercontent.com/46302511/107578561-2dd41c80-6bf4-11eb-909d-98de1d65c084.png)

**Comment by Lctrs** [comment]
You clearly don't want to do this as this allows Steam to access the whole system bus.

If you want to know what's the name of the required D-Bus service, you can run `flatpak run --log-system-bus com.valvesoftware.Steam` and look at the output.

**Comment by erazemk** [comment]
Thanks for the correction. I've checked the logs of the command you specified and I can't find any info relating to D-Bus services besides stuff about NetworkManager, but it did tell me that my controller is available at a specific path (`sdl://0`), so could that be what I should add instead of system-bus?

As a reference, here's the entire output: https://termbin.com/xaa6

If there was a D-Bus service for me to add it would probably be added using `--system-talk-name`, but how would I proceed in this case?

**Comment by PureTryOut** [comment]
I actually just noticed my PS3 controller _does_ get detected, seems the issue is specific to the DS4.

Running `flatpak run --log-system-bus com.valvesoftware.Steam` I get the following output when I connect a DS4 to my system:
```
B115: <- :1.11 signal org.freedesktop.UPower.DeviceAdded at /org/freedesktop/UPower
C24: -> org.freedesktop.UPower call org.freedesktop.UPower.GetDisplayDevice at /org/freedesktop/UPower
B118: <- :1.11 return from C24
C25: -> org.freedesktop.UPower call org.freedesktop.DBus.Properties.Get at /org/freedesktop/UPower/devices/DisplayDevice
B120: <- :1.11 return from C25
C26: -> org.freedesktop.UPower call org.freedesktop.UPower.EnumerateDevices at /org/freedesktop/UPower
B122: <- :1.11 return from C26
C27: -> org.freedesktop.UPower call org.freedesktop.DBus.Properties.Get at /org/freedesktop/UPower/devices/gaming_input_sony_controller_battery_70o20o84o62o46of4
B124: <- :1.11 return from C27
C28: -> org.freedesktop.UPower call org.freedesktop.DBus.Properties.Get at /org/freedesktop/UPower/devices/gaming_input_sony_controller_battery_70o20o84o62o46of4
B125: <- :1.11 return from C28
ioctl (GFEATURE): Broken pipe
```

**Comment by Lctrs** [comment]
@erazemk Have you disabled your workaround before running the command ?

@PureTryOut  `org.freedesktop.UPower` access is already enabled, so I believe that the problem comes from `ioctl (GFEATURE): Broken pipe`. Have you installed udev rules like this [one](https://github.com/rpmfusion/steam/blob/master/60-steam-input.rules) on the **host** ? It may be required to have controllers work.

**Comment by PureTryOut** [comment]
Ha, wouldn't you know, those udev rules work indeed! I guess Flatpaks can't install those? A bit annoying that besides installing the Flatpak you have to modify the host system manually as well.

**Comment by Lctrs** [comment]
You're right, flatpak can't install those.

There is already [an entry in the wiki](https://github.com/flathub/com.valvesoftware.Steam/wiki#my-controller-isnt-being-detected) for this issue. If @erazemk reports that installing those udev rules works for him too, this can be closed.

**Comment by erazemk** [comment]
> @erazemk Have you disabled your workaround before running the command ?

Oops, no, I haven't.

After re-running the command I get similar output as PureTryOut and my controller also automatically works (with the default permissions). I think my problem here was that I tried using a controller a while back and it didn't work then, so when I installed Steam yesterday I didn't even check if it worked, but just enabled the system bus since I remembered that fixed it last time. Or maybe Fedora just updated some udev rules and that's why it worked now.

In any case, thanks for your help @Lctrs, everything works normally for me. I'll close the pull request as well.

**Comment by Axis4s** [comment]
Im on EndeavourOS, how do i install these rules?

**Comment by Justinzobel** [comment]
> Im on EndeavourOS, how do i install these rules?

`sudo wget -O /etc/udev/rules.d/60-steam-input.rules https://raw.githubusercontent.com/ValveSoftware/steam-devices/master/60-steam-input.rules`

**Comment by ell1e** [comment]
Sorry if that's a silly question, but is such raw direct access to gamepad hardware actually needed and desired? Couldn't that actually used by some random background user to somehow confuse or mess up the gamepad maybe? What's with the `xpad` kernel module, which I assume works in a less raw way but is supposed to still provide the input in some usable form, is there a reason why Steam can't just access that like a "normal" application? This situation is a little confusing.
