### ISSUE TITLE
No access to local user directories

### ISSUE THREAD

**Issue by arielnmz** [flathub/com.valvesoftware.Steam#768]
The file selector does not have access to files and directories of the local user. For example the file selector in the Avatar section in Settings only shows a few User directories:

![image](https://user-images.githubusercontent.com/24735547/119908107-b1491d80-bf06-11eb-854f-a5958406600b.png)

For example this is my actual home directory:

![image](https://user-images.githubusercontent.com/24735547/119908304-2288d080-bf07-11eb-9c7a-27adce5e7673.png)

Moreover, the default directories do not seem to be accessible to the application, I can navigate to them but can't see or select any files in it. If I create a new directory or even copy-pasting a directory seems to work. Example:

Here are the files in both dirs, one was already there (`Imágenes`) and the other is a copy of that (`imags`):

![image](https://user-images.githubusercontent.com/24735547/119909172-1aca2b80-bf09-11eb-9cb1-b26e9597b1d6.png)

But the selector doesn't show anything:

![image](https://user-images.githubusercontent.com/24735547/119909225-3cc3ae00-bf09-11eb-8449-7ca6dbc6bf76.png)

Permissions and even Selinux contexts seem to be fine:

![image](https://user-images.githubusercontent.com/24735547/119909274-59f87c80-bf09-11eb-8b63-d5844f657825.png)

**Comment by alexpattyn** [comment]
Due to the sandbox flatpak provides (defined [here](https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.yml)), steam only has access to select directories by default. AFAIK steam doesn't make use of file portals so the dirs defined in the yaml file above are all that it can see. 

You can use [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) or the [cli](https://docs.flatpak.org/en/latest/sandbox-permissions.html) to add new directories.

**Comment by RobinJ1995** [comment]
This is most likely an intentional security feature. This means Steam, games, and potentially intrusive anti-cheat or other software cannot access files they do not need in order to function.

**Comment by nanonyme** [comment]
Access outside sandbox by default very limited since there's migration script that may break your home on first launch otherwise.
