### ISSUE TITLE
Steam has a black screen after starting from Desktop file

### ISSUE THREAD

**Issue by jkonecny12** [flathub/com.valvesoftware.Steam#819]
**Game information**
N/A this is happening to steam client not a game.

**Distribution name and version where applicable**
Fedora SilverBlue 34 with Sway WM

**Flatpak info**
```
$ flatpak --version
Flatpak 1.10.5
```
```
$ flatpak --gl-drivers
default
host
```

**Problem description**
Running Steam from a Desktop file will show a black screen.
![2021-10-29T15:24:55,132379415+02:00](https://user-images.githubusercontent.com/1643889/139442991-b91e1bc2-4455-4037-9147-485369429359.png)

However, when I switched to `Terminal=true` in the desktop file then the Steam is started as expected. The problem doesn't exists also when I run `flatpak run` command from the terminal. Not sure why this is happening. When I switch from Sway to Gnome Shell DE I'm also not experiencing this issue.

The desktop file worked without any problem in the past but some time ago it started to have this glitch (which I think happened because of freetype library incompatibility https://github.com/ValveSoftware/steam-for-linux/issues/7935), after the fix landed I'm still experiencing the issue from the Desktop file.

**Does this issue reproduce with native Steam**
Probably no.

**Comment by smcv** [comment]
> Running Steam from a Desktop file will show a black screen

This means the `steamwebhelper` process that renders the UI has crashed or failed to start. This is a symptom, not a root cause: there are lots of problems that can cause it, and they will all have similar user-facing results.

The Freetype issue that was fixed in the past is one of several possible root causes. I think you are now encountering a different root cause for the same symptom.

> However, when I switched to `Terminal=true` in the desktop file then the Steam is started as expected

This sounds very similar to <https://github.com/ValveSoftware/steam-for-linux/issues/8069>, which was caused by desktop environments starting Steam with invalid standard file descriptors. Some people who replied to that issue were using a misconfigured app-launcher under Sway, which can have similar symptoms.

If you look at `ls -l /proc/$pid/fd` where `$pid` is the process ID of the top-level Steam process, what are file descriptors 0, 1 and 2?

Please check that whatever app-launcher you are using under Sway is giving the app subprocess a reasonable file descriptor for each of `stdin`, `stdout` and `stderr` (file descriptors 0, 1, 2), and also check that the app-launcher is not parsing Steam's standard output and expecting it to be a stream of commands to run.

Workaround: temporarily edit the `.desktop` file generated by Flatpak to have `Terminal=true`, or to use `Exec=systemd-cat -t steam-flatpak flatpak run ...` instead of just `Exec=flatpak run ...` (so that Steam's output goes to the systemd journal instead of whatever it inherits from your app launcher).

A future version of Steam is likely to get its own workarounds for this. It's a little complicated because it needs to be worked around in several places, each with a different release schedule. This one that can cause this specific symptom is the `steamwebhelper.sh` script, which is part of the Steam client itself, and is automatically updated by Steam. You will get updates for that component sooner if you [opt-in to the Steam client beta channel](https://developer.valvesoftware.com/wiki/Betas), although at the time of writing, the latest beta does not have this workaround yet.

**Comment by jkonecny12** [comment]
> This means the `steamwebhelper` process that renders the UI has crashed or failed to start. This is a symptom, not a root cause: there are lots of problems that can cause it, and they will all have similar user-facing results.

Ohh thanks for explanation.

> This sounds very similar to [ValveSoftware/steam-for-linux#8069](https://github.com/ValveSoftware/steam-for-linux/issues/8069), which was caused by desktop environments starting Steam with invalid standard file descriptors. Some people who replied to that issue were using a misconfigured app-launcher under Sway, which can have similar symptoms.
> 
> If you look at `ls -l /proc/$pid/fd` where `$pid` is the process ID of the top-level Steam process, what are file descriptors 0, 1 and 2?

 ~  ls -l /proc/76212/fd/0
<snip> /proc/76212/fd/0 -> /dev/null
 ~  ls -l /proc/76212/fd/1
<snip> /proc/76212/fd/1 -> 'pipe:[1459834]'
 ~  ls -l /proc/76212/fd/2
<snip> /proc/76212/fd/2 -> 'socket:[40746]'

> Please check that whatever app-launcher you are using under Sway is giving the app subprocess a reasonable file descriptor for each of `stdin`, `stdout` and `stderr` (file descriptors 0, 1, 2), and also check that the app-launcher is not parsing Steam's standard output and expecting it to be a stream of commands to run.
 
> Workaround: temporarily edit the `.desktop` file generated by Flatpak to have `Terminal=true`, or to use `Exec=systemd-cat -t steam-flatpak flatpak run ...` instead of just `Exec=flatpak run ...` (so that Steam's output goes to the systemd journal instead of whatever it inherits from your app launcher).

I've tried the `systemd-cat` workaround and it helps. When I checked opened fds it changed `1` to socket.

> A future version of Steam is likely to get its own workarounds for this. It's a little complicated because it needs to be worked around in several places, each with a different release schedule. This one that can cause this specific symptom is the `steamwebhelper.sh` script, which is part of the Steam client itself, and is automatically updated by Steam. You will get updates for that component sooner if you [opt-in to the Steam client beta channel](https://developer.valvesoftware.com/wiki/Betas), although at the time of writing, the latest beta does not have this workaround yet.

Good idea.


Thanks a lot for your help. At least I know what is happening.

**Comment by smcv** [comment]
It sounds as though this is a bug or misconfiguration in your app launcher: it's starting Steam with stdout pointing to a pipe, but if it never reads from that pipe, then eventually Steam will fill up the pipe buffer (which is only a few K) and subsequent writes will fail.

A future version of Steam is likely to add workarounds for this, but this behaviour could easily break non-Steam apps too.

**Comment by jkonecny12** [comment]
I was able to resolve the issue. It was in my sway configuration:

```
set $menu rofi -theme Arc-Dark -modi combi -combi-modi "drun,run" -show combi #| xargs swaymsg exec --
```
The problematic part is commented here (pipe obviously). Seems that commenting it out is fine.

Thanks a lot for the explanation and pointers.
