### ISSUE TITLE
Missing libc.so.6 (beta branch)

### ISSUE THREAD

**Issue by CleoMenezes** [flathub/com.valvesoftware.Steam#828]
**Distribution name and version where applicable**
Fedora release 35 (Thirty Five)

**Flatpak info**
Flatpak 1.12.2
nvidia-495-44
default
host

**Problem description**
![image](https://user-images.githubusercontent.com/54215258/141037890-4c7d0711-ef30-4974-87f5-8106fad0a725.png)
After installing Steam from the beta branch and trying to open it, I get an error message about missing library libc.so.6

**Does this issue reproduce with native Steam**
I haven't tested it, but on the stable branch this doesn't happen.

**Comment by 1player** [comment]
I had the same issue on Fedora Kinoite, not sure what caused it, the command line `flatpak` command complained about a missing fedora package for some reason.

I fixed it by removing it and a couple other Flatpaks (not sure what, but I thought all my flatpaks were borked) and reinstalling them from the command line.

Not sure if it helps, but the gist is I don't think it's caused by Steam itself, but Fedora messing something up with the flatpak setup.

**Comment by Maltimore** [comment]
Is it possible that this is mentioned in the wiki?

https://github.com/flathub/com.valvesoftware.Steam/wiki#libso6-cannot-be-found

Disclaimer: I have no idea what I'm talking about. I just saw this issue and then read the wiki randomly, and thought it matches.

**Comment by gasinvein** [comment]
Make sure you have `org.freedesktop.Platform.Compat.i386//21.08` installed. It's not pulled in automatically if you've installed Steam flatpak `beta` branch.

**Comment by nanonyme** [comment]
Yeah, we should add note about non-stable branch installs to wiki. It's probably not that uncommon reason for this.

**Comment by nanonyme** [comment]
Added entry to main wiki, linked to relevant beta app page which already exists.
