### ISSUE TITLE
Steam is reporting older Mesa 21.3.8 is used while the installed Mesa version is 22.1.2

### ISSUE THREAD

**Issue by andreldmonteiro** [flathub/com.valvesoftware.Steam#916]
**Game information**

Steam itself: Help -> System Information

**Distribution name and version where applicable**

Fedora Workstation 36

**Flatpak info**

$ flatpak --version
Flatpak 1.12.7
$ flatpak --gl-drivers
default
host

**Problem description**

Steam reports it's using an older Mesa 21.3.8 version while the installed Mesa version is 22.1.2.

**Does this issue reproduce with native Steam**

Have not tested

**Comment by nanonyme** [comment]
Not a bug. Runtime has Mesa 21.3.8.

**Comment by andreldmonteiro** [comment]
Does this affect the performance and vulkan extensions available on steam?

**Comment by nanonyme** [comment]
Yes. Mesa is frozen until new runtime release at the end of August.

**Comment by andreldmonteiro** [comment]
This is quite an unfortunate situation for mesa users, are there any alternative ways to override this or has there been any discussion about this issue? This leaves mesa users at a disadvantage compared to Nvidia proprietary driver users.

**Comment by nanonyme** [comment]
Well, could potentially try https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/mesa-git. Mesa being frozen boils down to two reasons: updating involves ABI break in runtime and Mesa 22.0 drops support for all non-gallium drivers. Since there is no hardware available to test Mesa amber with, updating is not realistic without risking breaking graphics stack for some users.

**Comment by 1player** [comment]
FWIW I've been running Steam flatpak with mesa-git until recently, when I noticed another Flatpak application was broken because of a bug in mesa-git: https://github.com/Rafostar/clapper/issues/286

I guess the choice is between having bad performance in some Steam games or breaking some other flatpak. freedesktop 22.08 can't come soon enough.

**Comment by nanonyme** [comment]
Looks like mesa-git updating is broken. Will take a look.

**Comment by nanonyme** [comment]
mesa-git updates should now be happening as expected

**Comment by nanonyme** [comment]
Runtime beta is now out so you can now use https://github.com/flathub/com.valvesoftware.Steam/wiki/Using-beta-branch-of-this-app
