### ISSUE TITLE
Dark Souls III is broken with steam flatpak

### ISSUE THREAD

**Issue by kassindornelles** [flathub/com.valvesoftware.Steam#943]
**Game information**
Dark Souls III 
https://store.steampowered.com/app/374320/DARK_SOULS_III/

**Distribution name and version where applicable**
NAME="Fedora Linux"
VERSION="36 (KDE Plasma)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde

**Flatpak info**
 Flatpak 1.12.7
  flatpak --gl-drivers
default
host

**Problem description**
Character get's stuck in place and theres no known way to fix it
Video of the problem:
https://streamable.com/v81rvc

**Does this issue reproduce with native Steam**
no

**Comment by 1player** [comment]
Possibly related to #919?

**Comment by kassindornelles** [comment]
> Possibly related to #919?

yes, its the same issue

**Comment by noonsleeper** [comment]
I suffer this bug on Sekiro and Darksouls 3 and the same [workaround works on both](https://github.com/flathub/com.valvesoftware.Steam/issues/919#issuecomment-1207439274).

I tested installation of non-flatpak steam on another disk and non-standard path and this bug is present.
It's a common problem for Sekiro/Darksouls3 users on Windows as well, and was fixed for Elden Ring.

https://steamcommunity.com/app/374320/discussions/0/365163686082978255/
https://steamcommunity.com/app/374320/discussions/0/365163686080492353/
https://steamcommunity.com/app/814380/discussions/0/1771511442699878396/

**Comment by kassindornelles** [comment]
My issue is basically a duplicate of https://github.com/flathub/com.valvesoftware.Steam/issues/919 so i'm closing this one
